previews:
    generation: manual
    whatever: not a property
services:
    - type: web
      name: express
      runtime: node
      also: not-a-property
      plan: starter
      buildCommand: yarn --frozen-lockfile install
      startCommand: node app.js
      pullRequestPreviewsEnabled: true
      disk:
        name: My Disk
        mountPath: /var/data
        sizeGB: 1
      rootDir: carrot-atlas
version: ""
