https://github.com/wendorf/express-hello-world/tree/masterservices:
    - type: web
      name: express
      runtime: node
      plan: starter
      buildCommand: yarn --frozen-lockfile install
      startCommand: node app.js
      pullRequestPreviewsEnabled: true
      previews:
          generation: "off"
      disk:
        name: My Disk
        mountPath: /var/data
        sizeGB: 1
      rootDir: carrot-atlas
version: ""
