services:
- type: web
  name: express
  env: node
  plan: starter
  buildCommand: yarn --frozen-lockfile install
  startCommand: node app.js
  disk:
    name: My Disk
    mountPath: /var/data
    sizeGB: 1
  scaling:
    minInstances: 1         # Required
    maxInstances: 3         # Required
    targetMemoryPercent: 60 # Optional if targetCPUPercent is set (valid: 1-90)
    targetCPUPercent: 60    # Optional if targetMemory is set (valid: 1-90)
